name: publish-packages
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_HUB_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: |
          npm install
          npm install -g lerna

      - name: Extract current version
        id: get_version
        run: |
          CURRENT_VERSION=$(cat version | awk '{$1=$1;print}')
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - name: Config Git
        run: |
          git config --local user.name "polunzh"
          git config --local user.email "polunzh@qq.com"
          git checkout master
          git pull origin master

      - name: Publish to NPM
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          npm whoami
          echo "publish version ${CURRENT_VERSION}"
          lerna publish ${CURRENT_VERSION} --force-publish --yes

      - name: Update Readme
        run: |
          echo "test" >> README.md
          git add README.md
          git commit -m '[skip ci] update readme'

      - name: Push Readme
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_HUB_TOKEN }}
          branch: ${{ github.ref }}
